"""add gym amenities

Revision ID: 1b8b54236712
Revises: 4060ba49898f
Create Date: 2026-07-17 11:09:00.721388

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b8b54236712"
down_revision: str | Sequence[str] | None = "4060ba49898f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amenities",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=140), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("icon", sa.String(length=100), nullable=True),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_amenities")),
        sa.UniqueConstraint("slug", name="uq_amenities_slug"),
    )
    op.create_table(
        "gym_amenities",
        sa.Column("gym_id", sa.Uuid(), nullable=False),
        sa.Column("amenity_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["amenity_id"],
            ["amenities.id"],
            name=op.f("fk_gym_amenities_amenity_id_amenities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["gym_id"],
            ["gyms.id"],
            name=op.f("fk_gym_amenities_gym_id_gyms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gym_amenities")),
        sa.UniqueConstraint(
            "gym_id", "amenity_id", name="uq_gym_amenities_gym_amenity"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gym_amenities")
    op.drop_table("amenities")
    # ### end Alembic commands ###
