"""add gym pricing plans

Revision ID: b5ddd0cac5de
Revises: 0d66a60f95b3
Create Date: 2026-07-17 13:10:27.943720

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5ddd0cac5de"
down_revision: str | Sequence[str] | None = "0d66a60f95b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gym_day_passes",
        sa.Column("gym_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "currency", sa.String(length=3), server_default="KES", nullable=False
        ),
        sa.Column("validity_hours", sa.Integer(), server_default="24", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount > 0",
            name=op.f("ck_gym_day_passes_ck_gym_day_passes_amount_positive"),
        ),
        sa.CheckConstraint(
            "char_length(currency) = 3",
            name=op.f("ck_gym_day_passes_ck_gym_day_passes_currency_length"),
        ),
        sa.CheckConstraint(
            "validity_hours > 0",
            name=op.f("ck_gym_day_passes_ck_gym_day_passes_validity_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["gym_id"],
            ["gyms.id"],
            name=op.f("fk_gym_day_passes_gym_id_gyms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gym_day_passes")),
        sa.UniqueConstraint("gym_id", "name", name="uq_gym_day_passes_gym_name"),
    )
    op.create_index(
        op.f("ix_gym_day_passes_gym_id"), "gym_day_passes", ["gym_id"], unique=False
    )
    op.create_table(
        "gym_membership_plans",
        sa.Column("gym_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "currency", sa.String(length=3), server_default="KES", nullable=False
        ),
        sa.Column("billing_period", sa.String(length=30), nullable=False),
        sa.Column("access_days", sa.Integer(), nullable=True),
        sa.Column("visit_limit", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_featured", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "access_days IS NULL OR access_days > 0",
            name=op.f(
                "ck_gym_membership_plans_ck_gym_membership_plans_access_days_positive"
            ),
        ),
        sa.CheckConstraint(
            "amount > 0",
            name=op.f(
                "ck_gym_membership_plans_ck_gym_membership_plans_amount_positive"
            ),
        ),
        sa.CheckConstraint(
            "char_length(currency) = 3",
            name=op.f(
                "ck_gym_membership_plans_ck_gym_membership_plans_currency_length"
            ),
        ),
        sa.CheckConstraint(
            "visit_limit IS NULL OR visit_limit > 0",
            name=op.f(
                "ck_gym_membership_plans_ck_gym_membership_plans_visit_limit_positive"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["gym_id"],
            ["gyms.id"],
            name=op.f("fk_gym_membership_plans_gym_id_gyms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gym_membership_plans")),
        sa.UniqueConstraint("gym_id", "name", name="uq_gym_membership_plans_gym_name"),
    )
    op.create_index(
        op.f("ix_gym_membership_plans_gym_id"),
        "gym_membership_plans",
        ["gym_id"],
        unique=False,
    )
    op.create_table(
        "gym_membership_plan_benefits",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["gym_membership_plans.id"],
            name=op.f("fk_gym_membership_plan_benefits_plan_id_gym_membership_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gym_membership_plan_benefits")),
        sa.UniqueConstraint(
            "plan_id", "name", name="uq_gym_membership_plan_benefits_plan_name"
        ),
    )
    op.create_index(
        op.f("ix_gym_membership_plan_benefits_plan_id"),
        "gym_membership_plan_benefits",
        ["plan_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_gym_membership_plan_benefits_plan_id"),
        table_name="gym_membership_plan_benefits",
    )
    op.drop_table("gym_membership_plan_benefits")
    op.drop_index(
        op.f("ix_gym_membership_plans_gym_id"), table_name="gym_membership_plans"
    )
    op.drop_table("gym_membership_plans")
    op.drop_index(op.f("ix_gym_day_passes_gym_id"), table_name="gym_day_passes")
    op.drop_table("gym_day_passes")
    # ### end Alembic commands ###
