"""add gym business details

Revision ID: 4060ba49898f
Revises: 7a63d55a5773
Create Date: 2026-07-17 09:49:34.839561

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4060ba49898f"
down_revision: str | Sequence[str] | None = "7a63d55a5773"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gyms", sa.Column("legal_business_name", sa.String(length=200), nullable=True)
    )
    op.add_column(
        "gyms",
        sa.Column(
            "business_type",
            sa.Enum(
                "sole_proprietorship",
                "partnership",
                "limited_company",
                "non_profit",
                "other",
                name="gym_business_type",
                native_enum=False,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "gyms", sa.Column("registration_number", sa.String(length=100), nullable=True)
    )
    op.add_column("gyms", sa.Column("tax_number", sa.String(length=100), nullable=True))
    op.add_column(
        "gyms", sa.Column("contact_person_name", sa.String(length=150), nullable=True)
    )
    op.add_column(
        "gyms", sa.Column("contact_person_phone", sa.String(length=20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gyms", "contact_person_phone")
    op.drop_column("gyms", "contact_person_name")
    op.drop_column("gyms", "tax_number")
    op.drop_column("gyms", "registration_number")
    op.drop_column("gyms", "business_type")
    op.drop_column("gyms", "legal_business_name")
    # ### end Alembic commands ###
