"""add S3 upload tracking

Revision ID: 4a8f9bf6ca54
Revises: 8f4686ef2166
Create Date: 2026-07-17 23:37:11.489566

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a8f9bf6ca54"
down_revision: str | Sequence[str] | None = "8f4686ef2166"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_uploads",
        sa.Column("bucket", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "gym_verification_document", name="upload_purpose", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("gym_id", sa.Uuid(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "business_registration",
                "owner_identification",
                "tax_certificate",
                "operating_license",
                "proof_of_address",
                "other",
                name="gym_verification_document_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("original_filename", sa.String(length=200), nullable=False),
        sa.Column("declared_mime_type", sa.String(length=100), nullable=False),
        sa.Column("declared_size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "completed",
                "failed",
                "expired",
                "cancelled",
                name="upload_status",
                native_enum=False,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("etag", sa.String(length=128), nullable=True),
        sa.Column("verified_mime_type", sa.String(length=100), nullable=True),
        sa.Column("verified_size_bytes", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status != 'completed' OR "
            "(completed_at IS NOT NULL AND verified_mime_type IS NOT NULL "
            "AND verified_size_bytes IS NOT NULL)",
            name=op.f("ck_storage_uploads_storage_upload_completed_metadata_required"),
        ),
        sa.CheckConstraint(
            "declared_size_bytes > 0",
            name=op.f("ck_storage_uploads_storage_upload_declared_size_positive"),
        ),
        sa.CheckConstraint(
            "verified_size_bytes IS NULL OR verified_size_bytes > 0",
            name=op.f("ck_storage_uploads_storage_upload_verified_size_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["gym_id"],
            ["gyms.id"],
            name=op.f("fk_storage_uploads_gym_id_gyms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_storage_uploads_owner_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_storage_uploads")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_storage_uploads_storage_key")),
    )
    op.create_index(
        op.f("ix_storage_uploads_expires_at"),
        "storage_uploads",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_storage_uploads_gym_id"), "storage_uploads", ["gym_id"], unique=False
    )
    op.create_index(
        op.f("ix_storage_uploads_owner_user_id"),
        "storage_uploads",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_storage_uploads_purpose"), "storage_uploads", ["purpose"], unique=False
    )
    op.create_index(
        op.f("ix_storage_uploads_status"), "storage_uploads", ["status"], unique=False
    )
    op.alter_column(
        "auth_events",
        "event_type",
        existing_type=sa.VARCHAR(length=36),
        type_=sa.Enum(
            "otp_requested",
            "otp_request_blocked",
            "otp_verified",
            "otp_verification_failed",
            "otp_expired",
            "otp_attempts_exceeded",
            "login_succeeded",
            "login_denied",
            "password_changed",
            "super_admin_bootstrapped",
            "admin_created",
            "admin_status_changed",
            "admin_role_changed",
            "admin_operation_blocked",
            "gym_verification_document_registered",
            "gym_verification_submitted",
            "gym_verification_approved",
            "gym_verification_rejected",
            "storage_upload_initiated",
            "storage_upload_completed",
            "storage_upload_failed",
            "verification_document_download_requested",
            "token_refreshed",
            "token_refresh_failed",
            "logout",
            "logout_all",
            "session_revoked",
            "session_expired",
            name="auth_event_type",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    op.add_column(
        "gym_verification_documents",
        sa.Column("storage_bucket", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "gym_verification_documents",
        sa.Column("etag", sa.String(length=128), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gym_verification_documents", "etag")
    op.drop_column("gym_verification_documents", "storage_bucket")
    op.alter_column(
        "auth_events",
        "event_type",
        existing_type=sa.Enum(
            "otp_requested",
            "otp_request_blocked",
            "otp_verified",
            "otp_verification_failed",
            "otp_expired",
            "otp_attempts_exceeded",
            "login_succeeded",
            "login_denied",
            "password_changed",
            "super_admin_bootstrapped",
            "admin_created",
            "admin_status_changed",
            "admin_role_changed",
            "admin_operation_blocked",
            "gym_verification_document_registered",
            "gym_verification_submitted",
            "gym_verification_approved",
            "gym_verification_rejected",
            "storage_upload_initiated",
            "storage_upload_completed",
            "storage_upload_failed",
            "verification_document_download_requested",
            "token_refreshed",
            "token_refresh_failed",
            "logout",
            "logout_all",
            "session_revoked",
            "session_expired",
            name="auth_event_type",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=36),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_storage_uploads_status"), table_name="storage_uploads")
    op.drop_index(op.f("ix_storage_uploads_purpose"), table_name="storage_uploads")
    op.drop_index(
        op.f("ix_storage_uploads_owner_user_id"), table_name="storage_uploads"
    )
    op.drop_index(op.f("ix_storage_uploads_gym_id"), table_name="storage_uploads")
    op.drop_index(op.f("ix_storage_uploads_expires_at"), table_name="storage_uploads")
    op.drop_table("storage_uploads")
    # ### end Alembic commands ###
