"""add gym verification workflow

Revision ID: 51a41c7f7e32
Revises: b5ddd0cac5de
Create Date: 2026-07-17 14:53:42.052643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a41c7f7e32'
down_revision: Union[str, Sequence[str], None] = 'b5ddd0cac5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_verification_documents',
    sa.Column('gym_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_name', sa.String(length=200), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('file_size_bytes > 0', name=op.f('ck_gym_verification_documents_ck_gym_verification_documents_file_size_positive')),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_gym_verification_documents_gym_id_gyms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_gym_verification_documents_uploaded_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gym_verification_documents')),
    sa.UniqueConstraint('gym_id', 'document_type', name='uq_gym_verification_documents_gym_document_type')
    )
    op.create_index(op.f('ix_gym_verification_documents_gym_id'), 'gym_verification_documents', ['gym_id'], unique=False)
    op.create_table('gym_verification_reviews',
    sa.Column('gym_id', sa.Uuid(), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            decision = 'approve'\n            OR (\n                decision = 'reject'\n                AND rejection_reason IS NOT NULL\n                AND char_length(trim(rejection_reason)) > 0\n            )\n            ", name=op.f('ck_gym_verification_reviews_ck_gym_verification_reviews_rejection_reason_required')),
    sa.CheckConstraint("decision IN ('approve', 'reject')", name=op.f('ck_gym_verification_reviews_ck_gym_verification_reviews_decision_valid')),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_gym_verification_reviews_gym_id_gyms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_gym_verification_reviews_reviewed_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gym_verification_reviews'))
    )
    op.create_index(op.f('ix_gym_verification_reviews_gym_id'), 'gym_verification_reviews', ['gym_id'], unique=False)
    op.add_column('gyms', sa.Column('verification_submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('gyms', sa.Column('verification_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('gyms', sa.Column('verification_rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gyms', 'verification_rejection_reason')
    op.drop_column('gyms', 'verification_reviewed_at')
    op.drop_column('gyms', 'verification_submitted_at')
    op.drop_index(op.f('ix_gym_verification_reviews_gym_id'), table_name='gym_verification_reviews')
    op.drop_table('gym_verification_reviews')
    op.drop_index(op.f('ix_gym_verification_documents_gym_id'), table_name='gym_verification_documents')
    op.drop_table('gym_verification_documents')
    # ### end Alembic commands ###
