"""create gyms and gym ownership

Revision ID: 7a63d55a5773
Revises: a54a7f572fdd
Create Date: 2026-07-16 22:40:15.297912

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a63d55a5773"
down_revision: str | Sequence[str] | None = "a54a7f572fdd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gyms",
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("address_line", sa.String(length=300), nullable=True),
        sa.Column("neighbourhood", sa.String(length=120), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column(
            "country_code", sa.String(length=2), server_default="KE", nullable=False
        ),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("logo_url", sa.String(length=1000), nullable=True),
        sa.Column("cover_photo_url", sa.String(length=1000), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "pending_verification",
                "active",
                "suspended",
                "rejected",
                "deactivated",
                name="gym_status",
                native_enum=False,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "verification_status",
            sa.Enum(
                "not_submitted",
                "pending",
                "under_review",
                "approved",
                "rejected",
                name="gym_verification_status",
                native_enum=False,
            ),
            server_default="not_submitted",
            nullable=False,
        ),
        sa.Column(
            "onboarding_step",
            sa.Enum(
                "basic_information",
                "location",
                "business_details",
                "amenities",
                "operating_hours",
                "pricing",
                "verification",
                "completed",
                name="gym_onboarding_step",
                native_enum=False,
            ),
            server_default="basic_information",
            nullable=False,
        ),
        sa.Column(
            "onboarding_completed", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("is_listed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gyms")),
        sa.UniqueConstraint("slug", name=op.f("uq_gyms_slug")),
    )
    op.create_index(
        "ix_gyms_city_neighbourhood", "gyms", ["city", "neighbourhood"], unique=False
    )
    op.create_index(
        "ix_gyms_status_verification",
        "gyms",
        ["status", "verification_status"],
        unique=False,
    )
    op.create_table(
        "gym_operating_hours",
        sa.Column("gym_id", sa.Uuid(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("is_closed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("opens_at", sa.Time(), nullable=True),
        sa.Column("closes_at", sa.Time(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "day_of_week >= 0 AND day_of_week <= 6",
            name=op.f("ck_gym_operating_hours_day_of_week_valid"),
        ),
        sa.CheckConstraint(
            "is_closed = true OR (opens_at IS NOT NULL AND closes_at IS NOT NULL)",
            name=op.f("ck_gym_operating_hours_open_times_required_when_not_closed"),
        ),
        sa.ForeignKeyConstraint(
            ["gym_id"],
            ["gyms.id"],
            name=op.f("fk_gym_operating_hours_gym_id_gyms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gym_operating_hours")),
        sa.UniqueConstraint(
            "gym_id", "day_of_week", name="uq_gym_operating_hours_gym_day"
        ),
    )
    op.create_table(
        "gym_staff",
        sa.Column("gym_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "manager",
                "receptionist",
                "trainer",
                name="gym_staff_role",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "invited",
                "active",
                "suspended",
                "removed",
                name="gym_staff_status",
                native_enum=False,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "is_primary_owner", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["gym_id"],
            ["gyms.id"],
            name=op.f("fk_gym_staff_gym_id_gyms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_gym_staff_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gym_staff")),
        sa.UniqueConstraint("gym_id", "user_id", name="uq_gym_staff_gym_user"),
    )
    op.create_index(
        "ix_gym_staff_gym_role_status",
        "gym_staff",
        ["gym_id", "role", "status"],
        unique=False,
    )
    op.create_index(
        "ix_gym_staff_user_status", "gym_staff", ["user_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_gym_staff_user_status", table_name="gym_staff")
    op.drop_index("ix_gym_staff_gym_role_status", table_name="gym_staff")
    op.drop_table("gym_staff")
    op.drop_table("gym_operating_hours")
    op.drop_index("ix_gyms_status_verification", table_name="gyms")
    op.drop_index("ix_gyms_city_neighbourhood", table_name="gyms")
    op.drop_table("gyms")
    # ### end Alembic commands ###
