"""create user profiles and account roles

Revision ID: a54a7f572fdd
Revises: bff99336259b
Create Date: 2026-07-15 00:21:00.458390

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a54a7f572fdd"
down_revision: str | Sequence[str] | None = "bff99336259b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_account_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("member", "gym_owner", name="account_role", native_enum=False),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_account_roles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_account_roles")),
        sa.UniqueConstraint("user_id", "role", name="uq_user_account_roles_user_role"),
    )
    op.create_index(
        "ix_user_account_roles_user_active",
        "user_account_roles",
        ["user_id", "is_active"],
        unique=False,
    )
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("avatar_url", sa.String(length=1000), nullable=True),
        sa.Column("neighbourhood", sa.String(length=120), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column(
            "country_code", sa.String(length=2), server_default="KE", nullable=False
        ),
        sa.Column(
            "gender",
            sa.Enum(
                "male",
                "female",
                "other",
                "prefer_not_to_say",
                name="profile_gender",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column(
            "onboarding_status",
            sa.Enum(
                "account_selection_pending",
                "profile_setup_pending",
                "gym_setup_pending",
                "verification_pending",
                "completed",
                name="onboarding_status",
                native_enum=False,
            ),
            server_default="account_selection_pending",
            nullable=False,
        ),
        sa.Column(
            "onboarding_completed", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_profiles")),
        sa.UniqueConstraint("user_id", name=op.f("uq_user_profiles_user_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_profiles")
    op.drop_index("ix_user_account_roles_user_active", table_name="user_account_roles")
    op.drop_table("user_account_roles")
    # ### end Alembic commands ###
