"""create authentication audit events

Revision ID: bff99336259b
Revises: 3f061c3a167f
Create Date: 2026-07-13 01:06:44.489995

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bff99336259b"
down_revision: str | Sequence[str] | None = "3f061c3a167f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_events",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("challenge_id", sa.Uuid(), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "otp_requested",
                "otp_request_blocked",
                "otp_verified",
                "otp_verification_failed",
                "otp_expired",
                "otp_attempts_exceeded",
                "login_succeeded",
                "login_denied",
                "token_refreshed",
                "token_refresh_failed",
                "logout",
                "logout_all",
                "session_revoked",
                "session_expired",
                name="auth_event_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "success",
                "failure",
                "blocked",
                name="auth_event_outcome",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["challenge_id"],
            ["otp_challenges.id"],
            name=op.f("fk_auth_events_challenge_id_otp_challenges"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["refresh_sessions.id"],
            name=op.f("fk_auth_events_session_id_refresh_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_auth_events_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_events")),
    )
    op.create_index(
        op.f("ix_auth_events_challenge_id"),
        "auth_events",
        ["challenge_id"],
        unique=False,
    )
    op.create_index(
        "ix_auth_events_phone_created_at",
        "auth_events",
        ["phone_number", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_events_session_id"), "auth_events", ["session_id"], unique=False
    )
    op.create_index(
        "ix_auth_events_type_created_at",
        "auth_events",
        ["event_type", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_auth_events_user_created_at",
        "auth_events",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_events_user_id"), "auth_events", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auth_events_user_id"), table_name="auth_events")
    op.drop_index("ix_auth_events_user_created_at", table_name="auth_events")
    op.drop_index("ix_auth_events_type_created_at", table_name="auth_events")
    op.drop_index(op.f("ix_auth_events_session_id"), table_name="auth_events")
    op.drop_index("ix_auth_events_phone_created_at", table_name="auth_events")
    op.drop_index(op.f("ix_auth_events_challenge_id"), table_name="auth_events")
    op.drop_table("auth_events")
    # ### end Alembic commands ###
