"""add waiting verification onboarding state

Revision ID: ed00cf268c84
Revises: 4a8f9bf6ca54
Create Date: 2026-07-18 22:56:07.912889

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed00cf268c84"
down_revision: str | Sequence[str] | None = "4a8f9bf6ca54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "gyms",
        "onboarding_step",
        existing_type=sa.VARCHAR(length=17),
        type_=sa.Enum(
            "basic_information",
            "location",
            "business_details",
            "amenities",
            "operating_hours",
            "pricing",
            "verification",
            "waiting_for_verification",
            "completed",
            name="gym_onboarding_step",
            native_enum=False,
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'basic_information'::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "gyms",
        "onboarding_step",
        existing_type=sa.Enum(
            "basic_information",
            "location",
            "business_details",
            "amenities",
            "operating_hours",
            "pricing",
            "verification",
            "waiting_for_verification",
            "completed",
            name="gym_onboarding_step",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=17),
        existing_nullable=False,
        existing_server_default=sa.text("'basic_information'::character varying"),
    )
    # ### end Alembic commands ###
